"""
Video Renderer Tool.

Renders a video script (JSON) generated by visual_engine.py into an MP4 file using FFmpeg.
Requires FFmpeg to be installed and available in PATH.

Usage:
    python tools/render_video.py <path_to_video_script.json>
"""

import json
import logging
import subprocess
import sys
from pathlib import Path

# Add project root to path
sys.path.append(str(Path(__file__).parent.parent))

from reporting.visual_engine import VideoScript, VideoScene

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("VideoRenderer")


def load_script(json_path: str) -> VideoScript:
    """Load VideoScript from JSON."""
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    script = VideoScript(
        width=data.get("width", 1080),
        height=data.get("height", 1920),
        fps=data.get("fps", 30),
        background_color=data.get("background", "#121218"),
    )
    
    # Add scenes
    for scene_data in data.get("scenes", []):
        script.add_scene(
            duration=scene_data["duration"],
            text=scene_data["text"],
            animation=scene_data.get("animation", "fade_in"),
            position=scene_data.get("position", "center"),
            font_size=scene_data.get("font_size", 48),
            color=scene_data.get("color", "#FFFFFF"),
        )
        
    return script


def render(json_path: str):
    """Render video using FFmpeg."""
    logger.info(f"Loading script: {json_path}")
    script = load_script(json_path)
    
    output_path = Path(json_path).with_suffix(".mp4")
    logger.info(f"Target output: {output_path}")
    
    try:
        commands = script.to_ffmpeg_commands(output_path)
        
        logger.info("Running FFmpeg...")
        # commands is a list [ffmpeg, -y, ...]
        subprocess.run(commands, check=True)
        
        logger.info(f"✅ Video rendered successfully: {output_path}")
        
    except subprocess.CalledProcessError as e:
        logger.error(f"FFmpeg failed: {e}")
        logger.error("Make sure FFmpeg is installed and accessible in PATH.")
    except Exception as e:
        logger.error(f"Render failed: {e}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python tools/render_video.py <path_to_json>")
        sys.exit(1)
        
    target_file = sys.argv[1]
    render(target_file)
